//tablecrafting defines
#define CAT_NONE	""
#define CAT_WEAPONRY	"Weaponry"
#define CAT_WEAPON	"Ranged Weapons"
#define CAT_MELEE	"Melee Weapons"
#define CAT_AMMO	"Ammo & Cells"
#define CAT_MISCWEP	"Weapons Misc"
#define CAT_PARTS	"Weapon Parts"
#define CAT_CRAFTING	"Crafting"
#define CAT_ROBOT	"Electronics & Robots"
#define CAT_FORGING	"Forging & Smithing"
#define CAT_MISC	"Misc"
#define CAT_SCAVENGING	"Scavenging & Tinkering"
#define CAT_MISCELLANEOUS	"Miscellaneous"
#define CAT_TOOL	"Tools & Workbench"
#define CAT_FURNITURE	"Burial & Execution"
#define CAT_FARMING	"Farming"
#define CAT_PRIMAL	"Primal"
#define CAT_TRIBAL "Tribal"
#define CAT_CLOTHING	"Clothing"
#define CAT_FOOD	"Foods"
#define CAT_WASTEFOOD	"Food Wasteland"
#define CAT_BREAD	"Food Bread"
#define CAT_BURGER	"Food Old World"
#define CAT_CAKE	"Food Cakes"
#define CAT_DONUT	"Food Donuts"
#define CAT_EGG	"Food Egg-Based"
#define CAT_MEAT	"Food Meats"
#define CAT_MEXICAN	"Food Mexican"
#define CAT_MISCFOOD	"Food Misc"
#define CAT_PASTRY	"Food Pastries"
#define CAT_PIE	"Food Pies & Sweets"
#define CAT_PIZZA	"Food Pizzas"
#define CAT_SALAD	"Food Salads"
#define CAT_SEAFOOD	"Food Seafood"
#define CAT_SANDWICH	"Food Sandwiches"
#define CAT_SOUP	"Food Soups"
#define CAT_SPAGHETTI	"Food Spaghettis"
#define CAT_ICE	"Food Frozen"
#define CAT_MEDICAL "Medical"
#define CAT_BOTTLE "Bottling"
#define CAT_GENCLOTHES "General Clothing"
#define CAT_ARMOR "Armor"
#define CAT_BELTS	"Belts"
#define CAT_WASTELAND	"Wasteland Clothing"
#define CAT_SHOES "Shoes"
#define CAT_MISCCLOTHING "Misc Clothing"
#define CAT_DRINK "Drinks"
#define CAT_EXPLOSIVE "Explosives"

/datum/crafting_recipe
	var/subcategory = CAT_NONE